### ISSUE TITLE
Vim(call):E488: Trailing characters in windows

### ISSUE THREAD

**Issue by prabirshrestha** [tsufeki/asyncomplete-fuzzy-match#3]
Seems like in windows the bug comes pretty often and makes it almost impossible to us asyncomplete-fuzzy-match.

Made some changes here to log and here is what i see.

```
function! s:handle_response(data) abort
  call asyncomplete#log('s:handle_response()', a:data)
  try
    for l:chunk in a:data
      if l:chunk !=# ''
        let s:buffer .= l:chunk
      elseif s:buffer !=# '' && !empty(s:complete_options)
        call asyncomplete#log(s:buffer)
        call asyncomplete#preprocess_complete(s:complete_options, json_decode(s:buffer)) 
        let s:buffer = ''
        let s:complete_options = {}
      endif
    endfor
  catch /.*/
    call asyncomplete#log(v:exception, v:throwpoint, s:buffer)
    echom v:exception
  endtry
endfunction
```

Notice the trailing empty array.

```
["s:handle_response()",["[]",""]]

[
  "[{\"word\":\"stop\",\"dup\":1,\"menu\":\"st[op]\",\"kind\":\"operator\",\"user_data\":\"{\\\"vim-lsp/key\\\":\\\"132\\\"}\",\"icase\":1,\"empty\":1,\"info\":\"suspend the editor or escape to a shell\",\"abbr\":\"stop\"}][][]"
]

["Vim(call):E488: Trailing characters","function <SNR>76_out_cb[2]..<lambda>2[1]..<SNR>75_handle_response, line 8"
```

This cause Vim(call):E488: Trailing characters error which can be reproduced with `echom json_decode("[][]")`

**Comment by tsufeki** [comment]
Thanks for the detailed report. I pushed a fix 5b9a665, can you please check if it helps? I don't have easy access to a window machine.

**Comment by tsufeki** [comment]
Hmm, this fix probably isn't correct: the error happens when a request from asyncomplete comes before we've sent a response to the previous one, and currently we send *first* stale response with *second* complete_options and drop *second* response. Like this:

```
--> request1 options1
--> request2 options2
<-- response1 options2 (mismatched)
* drop response2
```

So I need to keep a queue to match responses to their options (4b3d2b3)

My question to you: should I send all responses back to asyncomplete or should I drop older responses when I know newer request is in progress? I'm not sure which would be better from asyncomplete's PoV.

```
--> request1 options1
--> request2 options2
here: send response1 options1 or drop?
<-- response2 options2 (always)
```

**Comment by prabirshrestha** [comment]
While asyncomplete does handle cases for older it is better to drop on your own since it is more accurate. Asyncomplete dropping might not always work as expected though it handles majority of the case.

One option instead of queue is to use request/response id similar to LSP. If the last request if is not the same drop it. If the ids are not the same drop it. This would be a breaking change on rust side but ok. I would personally also send method Name in the request so you can rank completed items higher. This is what vscode does does.

**Comment by prabirshrestha** [comment]
tried the branch. still not fixed.

**Comment by tsufeki** [comment]
Newline detection may be the culprit? I reworked it, can you try `queue` branch again? (together dropping by request id - you need to recompile rust).

**Comment by prabirshrestha** [comment]
It works in windows. Thanks for the quick fix.

**Comment by prabirshrestha** [comment]
Reopening. Not merged to master yet.
